name: CI

on:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action Files
        uses: actions/checkout@v4

      - uses: .//.github/actions/setup-python-uv-env
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Run tests
        run: uv run pytest

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action Files
        uses: actions/checkout@v4

      - uses: .//.github/actions/setup-python-uv-env
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Check formatting
        run: uv run ruff format --check .

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action Files
        uses: actions/checkout@v4
      - uses: .//.github/actions/setup-python-uv-env
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Lint
        run: uv run ruff check .

  type_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action Files
        uses: actions/checkout@v4

      - uses: .//.github/actions/setup-python-uv-env
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Type check
        run: uv run pyright
